// Mock catalog — deterministic, client-only data used as the fallback when no
// provider/backend is available (see CLAUDE.md section 4). Uses real-world factual
// metadata (artist / album / track names, years) across multiple scripts so
// mixed-script rendering can be evaluated; cover art is never reproduced (the app
// draws generated placeholders), and lyrics are ORIGINAL demo text.
//
// The exported MOCK arrays are cast to the vibe view-models at the bottom — this
// is the single fixture→view-model boundary (the raw shapes are looser, and the
// screens read display fields defensively with defaults).
import type { VibeArtist, VibeCollection, VibeTrack } from "./adapt";

// ---- base songs (real titles/albums, multilingual; enriched below) ----
const rawTracks = [
  // English — Bon Iver · Tame Impala · Radiohead · Burial · Beach House · Boards of Canada
  {
    id: "t1",
    title: "Holocene",
    artist: "Bon Iver",
    artistId: "a-boniver",
    album: "Bon Iver, Bon Iver",
    albumId: "al-boniver",
    duration: "5:36",
    durSec: 336,
    coverSeed: 0,
    added: "3 days ago",
    plays: "182,341,209",
  },
  {
    id: "t2",
    title: "Perth",
    artist: "Bon Iver",
    artistId: "a-boniver",
    album: "Bon Iver, Bon Iver",
    albumId: "al-boniver",
    duration: "4:39",
    durSec: 279,
    coverSeed: 0,
    added: "3 days ago",
    plays: "98,802,455",
  },
  {
    id: "t3",
    title: "Let It Happen",
    artist: "Tame Impala",
    artistId: "a-tame",
    album: "Currents",
    albumId: "al-currents",
    duration: "7:47",
    durSec: 467,
    coverSeed: 2,
    added: "1 week ago",
    plays: "421,987,322",
  },
  {
    id: "t4",
    title: "The Less I Know the Better",
    artist: "Tame Impala",
    artistId: "a-tame",
    album: "Currents",
    albumId: "al-currents",
    duration: "3:36",
    durSec: 216,
    coverSeed: 2,
    added: "1 week ago",
    plays: "1,402,118,004",
  },
  {
    id: "t5",
    title: "Weird Fishes / Arpeggi",
    artist: "Radiohead",
    artistId: "a-radio",
    album: "In Rainbows",
    albumId: "al-rainbows",
    duration: "5:18",
    durSec: 318,
    coverSeed: 6,
    added: "Apr 22, 2026",
    plays: "318,118,440",
  },
  {
    id: "t6",
    title: "Nude",
    artist: "Radiohead",
    artistId: "a-radio",
    album: "In Rainbows",
    albumId: "al-rainbows",
    duration: "4:15",
    durSec: 255,
    coverSeed: 6,
    added: "Apr 22, 2026",
    plays: "205,055,909",
  },
  {
    id: "t7",
    title: "Archangel",
    artist: "Burial",
    artistId: "a-burial",
    album: "Untrue",
    albumId: "al-untrue",
    duration: "3:57",
    durSec: 237,
    coverSeed: 10,
    added: "Apr 18, 2026",
    plays: "42,221,098",
  },
  {
    id: "t8",
    title: "Near Dark",
    artist: "Burial",
    artistId: "a-burial",
    album: "Untrue",
    albumId: "al-untrue",
    duration: "3:56",
    durSec: 236,
    coverSeed: 10,
    added: "Apr 18, 2026",
    plays: "19,907,221",
  },
  {
    id: "t9",
    title: "Myth",
    artist: "Beach House",
    artistId: "a-beach",
    album: "Bloom",
    albumId: "al-bloom",
    duration: "4:18",
    durSec: 258,
    coverSeed: 8,
    added: "Mar 30, 2026",
    plays: "159,902,344",
  },
  {
    id: "t10",
    title: "Lazuli",
    artist: "Beach House",
    artistId: "a-beach",
    album: "Bloom",
    albumId: "al-bloom",
    duration: "5:03",
    durSec: 303,
    coverSeed: 8,
    added: "Mar 30, 2026",
    plays: "44,455,008",
  },
  {
    id: "t11",
    title: "Roygbiv",
    artist: "Boards of Canada",
    artistId: "a-boc",
    album: "Music Has the Right to Children",
    albumId: "al-mhtr",
    duration: "2:31",
    durSec: 151,
    coverSeed: 4,
    added: "Mar 12, 2026",
    plays: "58,901,776",
  },
  {
    id: "t12",
    title: "Aquarius",
    artist: "Boards of Canada",
    artistId: "a-boc",
    album: "Music Has the Right to Children",
    albumId: "al-mhtr",
    duration: "5:58",
    durSec: 358,
    coverSeed: 4,
    added: "Mar 12, 2026",
    plays: "31,102,558",
  },
  {
    id: "t13",
    title: "Towers",
    artist: "Bon Iver",
    artistId: "a-boniver",
    album: "Bon Iver, Bon Iver",
    albumId: "al-boniver",
    duration: "4:21",
    durSec: 261,
    coverSeed: 0,
    added: "3 days ago",
    plays: "21,812,001",
  },
  {
    id: "t14",
    title: "Wild",
    artist: "Beach House",
    artistId: "a-beach",
    album: "Bloom",
    albumId: "al-bloom",
    duration: "4:54",
    durSec: 294,
    coverSeed: 8,
    added: "Mar 30, 2026",
    plays: "37,401,225",
  },
  {
    id: "t15",
    title: "Eventually",
    artist: "Tame Impala",
    artistId: "a-tame",
    album: "Currents",
    albumId: "al-currents",
    duration: "5:19",
    durSec: 319,
    coverSeed: 2,
    added: "1 week ago",
    plays: "188,331,901",
  },

  // Mandarin — 周杰伦 / 陈绮贞
  {
    id: "t16",
    title: "晴天",
    artist: "周杰伦",
    artistId: "a-jay",
    album: "叶惠美",
    albumId: "al-yhm",
    duration: "4:29",
    durSec: 269,
    coverSeed: 7,
    added: "Feb 18, 2026",
    plays: "612,440,118",
  },
  {
    id: "t17",
    title: "以父之名",
    artist: "周杰伦",
    artistId: "a-jay",
    album: "叶惠美",
    albumId: "al-yhm",
    duration: "5:42",
    durSec: 342,
    coverSeed: 7,
    added: "Feb 18, 2026",
    plays: "204,889,201",
  },
  {
    id: "t18",
    title: "旅行的意义",
    artist: "陈绮贞",
    artistId: "a-cheer",
    album: "华丽的冒险",
    albumId: "al-adventure",
    duration: "4:13",
    durSec: 253,
    coverSeed: 3,
    added: "Feb 02, 2026",
    plays: "98,332,665",
  },

  // Japanese — 宇多田ヒカル / 米津玄師
  {
    id: "t19",
    title: "Automatic",
    artist: "宇多田ヒカル",
    artistId: "a-utada",
    album: "First Love",
    albumId: "al-firstlove",
    duration: "4:34",
    durSec: 274,
    coverSeed: 5,
    added: "Jan 20, 2026",
    plays: "143,776,540",
  },
  {
    id: "t20",
    title: "First Love",
    artist: "宇多田ヒカル",
    artistId: "a-utada",
    album: "First Love",
    albumId: "al-firstlove",
    duration: "4:18",
    durSec: 258,
    coverSeed: 5,
    added: "Jan 20, 2026",
    plays: "221,654,990",
  },
  {
    id: "t21",
    title: "Lemon",
    artist: "米津玄師",
    artistId: "a-yonezu",
    album: "BOOTLEG",
    albumId: "al-bootleg",
    duration: "4:16",
    durSec: 256,
    coverSeed: 9,
    added: "Jan 06, 2026",
    plays: "988,120,773",
  },

  // Korean — IU
  {
    id: "t22",
    title: "Palette (feat. G-DRAGON)",
    artist: "IU",
    artistId: "a-iu",
    album: "Palette",
    albumId: "al-palette",
    duration: "3:42",
    durSec: 222,
    coverSeed: 11,
    added: "Dec 28, 2025",
    plays: "176,540,887",
  },
  {
    id: "t23",
    title: "밤편지",
    artist: "IU",
    artistId: "a-iu",
    album: "Palette",
    albumId: "al-palette",
    duration: "3:36",
    durSec: 216,
    coverSeed: 11,
    added: "Dec 28, 2025",
    plays: "210,998,332",
  },

  // Cantonese — 陳奕迅
  {
    id: "t24",
    title: "浮誇",
    artist: "陳奕迅",
    artistId: "a-eason",
    album: "U87",
    albumId: "al-u87",
    duration: "4:50",
    durSec: 290,
    coverSeed: 1,
    added: "Dec 11, 2025",
    plays: "133,220,545",
  },

  // French — Daft Punk
  {
    id: "t25",
    title: "One More Time",
    artist: "Daft Punk",
    artistId: "a-daft",
    album: "Discovery",
    albumId: "al-discovery",
    duration: "5:20",
    durSec: 320,
    coverSeed: 3,
    added: "Nov 30, 2025",
    plays: "501,776,330",
  },
  {
    id: "t26",
    title: "Digital Love",
    artist: "Daft Punk",
    artistId: "a-daft",
    album: "Discovery",
    albumId: "al-discovery",
    duration: "4:58",
    durSec: 298,
    coverSeed: 3,
    added: "Nov 30, 2025",
    plays: "287,540,119",
  },
];

// ---- model facets used to enrich each Song ----
const VERSIONS: Record<string, string> = { t6: "live", t15: "remix" }; // non-studio Recording versions
const VIP_ONLY = new Set(["t5", "t9", "t10", "t14", "t22", "t23", "t24"]); // member-gated songs (mixed scripts)
const UNAVAILABLE = new Set(["t13", "t17"]); // greyed out by rights/region
const GENRE_BY_ARTIST: Record<string, string[]> = {
  "a-boniver": ["Folk", "Indie"],
  "a-tame": ["Psychedelic", "Electronic"],
  "a-radio": ["Alternative", "Rock"],
  "a-burial": ["Electronic", "Ambient"],
  "a-beach": ["Dream Pop", "Indie"],
  "a-boc": ["Electronic", "Ambient"],
  "a-jay": ["Mandopop", "Pop"],
  "a-cheer": ["Folk", "Indie"],
  "a-utada": ["J-Pop", "R&B"],
  "a-yonezu": ["J-Pop", "Rock"],
  "a-iu": ["K-Pop", "Ballad"],
  "a-eason": ["Cantopop", "Pop"],
  "a-daft": ["Electronic", "House"],
};
const LANG_BY_ARTIST: Record<string, string> = {
  "a-boniver": "English",
  "a-tame": "English",
  "a-radio": "English",
  "a-burial": "English",
  "a-beach": "English",
  "a-boc": "English",
  "a-jay": "Mandarin",
  "a-cheer": "Mandarin",
  "a-utada": "Japanese",
  "a-yonezu": "Japanese",
  "a-iu": "Korean",
  "a-eason": "Cantonese",
  "a-daft": "French",
};
const PRODUCER_BY_ARTIST: Record<string, string> = {
  "a-boniver": "Justin Vernon",
  "a-tame": "Kevin Parker",
  "a-radio": "Nigel Godrich",
  "a-burial": "Burial",
  "a-beach": "Beach House",
  "a-boc": "Boards of Canada",
  "a-jay": "周杰伦",
  "a-cheer": "陈绮贞",
  "a-utada": "宇多田ヒカル",
  "a-yonezu": "米津玄師",
  "a-iu": "IU",
  "a-eason": "C.Y. Kong",
  "a-daft": "Daft Punk",
};
const MOOD_CYCLE = [["Calm"], ["Melancholy"], ["Hype"], ["Romantic"], ["Focus"], ["Nostalgic"]];
const QUAL_CYCLE = ["Hi-Res", "SQ", "HQ", "SQ", "Hi-Res"];
const QUAL_TIERS: Record<string, string[]> = {
  HQ: ["STD", "HQ"],
  SQ: ["STD", "HQ", "SQ"],
  "Hi-Res": ["STD", "HQ", "SQ", "Hi-Res"],
};

const enrich = (t: any, i: number) => {
  const q = QUAL_CYCLE[i % QUAL_CYCLE.length];
  return {
    ...t,
    artistIds: [t.artistId], // primary (+ featured when present)
    featArtistId: null,
    version: VERSIONS[t.id] || "studio", // studio | live | remix | acoustic
    language: LANG_BY_ARTIST[t.artistId] || "English",
    genres: GENRE_BY_ARTIST[t.artistId] || ["Indie"],
    moods: MOOD_CYCLE[i % MOOD_CYCLE.length],
    credits: {
      lyrics: t.artist,
      music: t.artist,
      producer: PRODUCER_BY_ARTIST[t.artistId] || t.artist,
    },
    quality: q, // best tier available
    qualities: QUAL_TIERS[q],
    vipOnly: VIP_ONLY.has(t.id),
    available: !UNAVAILABLE.has(t.id),
    explicit: false,
  };
};

const tracks = rawTracks.map(enrich);

// Home/library fall back to the real catalog shape; only the flat track pool is
// consumed (Library songs, History seeding) when the provider is offline.
const data = {
  allTracks: tracks as unknown as VibeTrack[],
};

// ---- Organization · Playlist (curated + generated) ----
// kind "Made For Lily" = generated (DailyMix); "Playlist" = curated.
const playlists = [
  {
    id: "liked",
    name: "Liked Songs",
    kind: "Playlist",
    owner: "Lily",
    coverSeed: 0,
    gradient: ["#4a3aa6", "#8b7adc"],
    pinned: true,
    description: "Everything you've hearted, in one place.",
    tracks: tracks.slice(0, 8),
  },
  {
    id: "dm1",
    name: "Daily Mix 1",
    kind: "Made For Lily",
    owner: "Sonance",
    coverSeed: 1,
    gradient: ["#3b1d4a", "#1ed760"],
    pinned: true,
    generated: true,
    refreshCycle: "daily",
    description: "Beach House, 周杰伦, Tame Impala and more, refreshed for you.",
    tracks: tracks.slice(2, 12),
  },
  {
    id: "dw",
    name: "Discover Weekly",
    kind: "Made For Lily",
    owner: "Sonance",
    coverSeed: 11,
    gradient: ["#1a0d3a", "#7755ff"],
    generated: true,
    refreshCycle: "weekly",
    description: "Your weekly mixtape of fresh music. Updated every Monday.",
    tracks: tracks.slice(14, 24),
  },
  {
    id: "focus",
    name: "Deep Focus",
    kind: "Playlist",
    owner: "Sonance",
    coverSeed: 2,
    gradient: ["#0d3a3a", "#7adfae"],
    description: "Long-form ambient and post-rock to keep you in the zone.",
    tracks: tracks.slice(4, 12),
  },
  {
    id: "evening",
    name: "晚间原声 · Evening",
    kind: "Playlist",
    owner: "Sonance",
    coverSeed: 3,
    gradient: ["#3a0d10", "#f3727f"],
    description: "Wind down. Soft guitars and softer vocals.",
    tracks: tracks.slice(15, 22),
  },
  {
    id: "indie",
    name: "Indie Mix",
    kind: "Playlist",
    owner: "Lily",
    coverSeed: 4,
    gradient: ["#1a2e5a", "#539df5"],
    description: "Your indie staples plus a few new things.",
    tracks: tracks.slice(3, 10),
  },
  {
    id: "drive",
    name: "夜兜风 · Drive",
    kind: "Playlist",
    owner: "Lily",
    coverSeed: 5,
    gradient: ["#3a2a0d", "#dd9944"],
    description: "Songs to take a long drive to.",
    tracks: [tracks[15], tracks[23], tracks[24], tracks[2], tracks[20], tracks[8]],
  },
];

// ---- Catalog · Album (consumer-merged Album+Release; type & label kept) ----
const albums = [
  {
    id: "al-boniver",
    name: "Bon Iver, Bon Iver",
    artist: "Bon Iver",
    artistId: "a-boniver",
    year: 2011,
    type: "Album",
    label: "Jagjaguwar",
    coverSeed: 0,
    gradient: ["#1a0d3a", "#7755ff"],
    tracks: tracks.filter((t) => t.albumId === "al-boniver"),
  },
  {
    id: "al-currents",
    name: "Currents",
    artist: "Tame Impala",
    artistId: "a-tame",
    year: 2015,
    type: "Album",
    label: "Modular",
    coverSeed: 2,
    gradient: ["#3a0d10", "#f3727f"],
    tracks: tracks.filter((t) => t.albumId === "al-currents"),
  },
  {
    id: "al-rainbows",
    name: "In Rainbows",
    artist: "Radiohead",
    artistId: "a-radio",
    year: 2007,
    type: "Album",
    label: "XL Recordings",
    coverSeed: 6,
    gradient: ["#0d1f3a", "#88ccff"],
    tracks: tracks.filter((t) => t.albumId === "al-rainbows"),
  },
  {
    id: "al-untrue",
    name: "Untrue",
    artist: "Burial",
    artistId: "a-burial",
    year: 2007,
    type: "Album",
    label: "Hyperdub",
    coverSeed: 10,
    gradient: ["#101012", "#8aa0b5"],
    tracks: tracks.filter((t) => t.albumId === "al-untrue"),
  },
  {
    id: "al-bloom",
    name: "Bloom",
    artist: "Beach House",
    artistId: "a-beach",
    year: 2012,
    type: "Album",
    label: "Sub Pop",
    coverSeed: 8,
    gradient: ["#2a0d3a", "#a44dff"],
    tracks: tracks.filter((t) => t.albumId === "al-bloom"),
  },
  {
    id: "al-mhtr",
    name: "Music Has the Right to Children",
    artist: "Boards of Canada",
    artistId: "a-boc",
    year: 1998,
    type: "Album",
    label: "Warp",
    coverSeed: 4,
    gradient: ["#4a3a0d", "#ffa42b"],
    tracks: tracks.filter((t) => t.albumId === "al-mhtr"),
  },
  {
    id: "al-yhm",
    name: "叶惠美",
    artist: "周杰伦",
    artistId: "a-jay",
    year: 2003,
    type: "Album",
    label: "阿尔发音乐",
    coverSeed: 7,
    gradient: ["#2a0d3a", "#a44dff"],
    tracks: tracks.filter((t) => t.albumId === "al-yhm"),
  },
  {
    id: "al-adventure",
    name: "华丽的冒险",
    artist: "陈绮贞",
    artistId: "a-cheer",
    year: 2005,
    type: "Album",
    label: "好小气音乐",
    coverSeed: 3,
    gradient: ["#0a3a2a", "#1ed760"],
    tracks: tracks.filter((t) => t.albumId === "al-adventure"),
  },
  {
    id: "al-firstlove",
    name: "First Love",
    artist: "宇多田ヒカル",
    artistId: "a-utada",
    year: 1999,
    type: "Album",
    label: "東芝EMI",
    coverSeed: 5,
    gradient: ["#3a0d10", "#f3727f"],
    tracks: tracks.filter((t) => t.albumId === "al-firstlove"),
  },
  {
    id: "al-bootleg",
    name: "BOOTLEG",
    artist: "米津玄師",
    artistId: "a-yonezu",
    year: 2017,
    type: "Album",
    label: "Sony Music",
    coverSeed: 9,
    gradient: ["#240b04", "#ff8a3c"],
    tracks: tracks.filter((t) => t.albumId === "al-bootleg"),
  },
  {
    id: "al-palette",
    name: "Palette",
    artist: "IU",
    artistId: "a-iu",
    year: 2017,
    type: "Album",
    label: "EDAM Entertainment",
    coverSeed: 11,
    gradient: ["#3a0d28", "#ff62a8"],
    tracks: tracks.filter((t) => t.albumId === "al-palette"),
  },
  {
    id: "al-u87",
    name: "U87",
    artist: "陳奕迅",
    artistId: "a-eason",
    year: 2005,
    type: "Album",
    label: "英皇娱乐",
    coverSeed: 1,
    gradient: ["#101012", "#8aa0b5"],
    tracks: tracks.filter((t) => t.albumId === "al-u87"),
  },
  {
    id: "al-discovery",
    name: "Discovery",
    artist: "Daft Punk",
    artistId: "a-daft",
    year: 2001,
    type: "Album",
    label: "Virgin",
    coverSeed: 3,
    gradient: ["#13031f", "#b15cff"],
    tracks: tracks.filter((t) => t.albumId === "al-discovery"),
  },
];

// ---- Catalog · Artist (performer; followable) ----
const artists = [
  {
    id: "a-boniver",
    name: "Bon Iver",
    listeners: "8,142,000",
    verified: true,
    coverSeed: 0,
    gradient: ["#1a0d3a", "#7755ff"],
    genres: GENRE_BY_ARTIST["a-boniver"],
    bio: "Justin Vernon's project, born in a Wisconsin cabin. Falsetto, folk, and electronics.",
  },
  {
    id: "a-tame",
    name: "Tame Impala",
    listeners: "22,030,000",
    verified: true,
    coverSeed: 2,
    gradient: ["#3a0d10", "#f3727f"],
    genres: GENRE_BY_ARTIST["a-tame"],
    bio: "Kevin Parker's one-man psychedelic studio project from Perth, Australia.",
  },
  {
    id: "a-radio",
    name: "Radiohead",
    listeners: "31,540,000",
    verified: true,
    coverSeed: 6,
    gradient: ["#0d1f3a", "#88ccff"],
    genres: GENRE_BY_ARTIST["a-radio"],
    bio: "Oxfordshire five-piece, restless pioneers of art rock since the late '80s.",
  },
  {
    id: "a-burial",
    name: "Burial",
    listeners: "3,210,000",
    verified: false,
    coverSeed: 10,
    gradient: ["#101012", "#8aa0b5"],
    genres: GENRE_BY_ARTIST["a-burial"],
    bio: "William Bevan. Crackle, rain, and ghostly vocals from South London.",
  },
  {
    id: "a-beach",
    name: "Beach House",
    listeners: "9,870,000",
    verified: true,
    coverSeed: 8,
    gradient: ["#2a0d3a", "#a44dff"],
    genres: GENRE_BY_ARTIST["a-beach"],
    bio: "Baltimore dream-pop duo: Victoria Legrand and Alex Scally.",
  },
  {
    id: "a-boc",
    name: "Boards of Canada",
    listeners: "4,560,000",
    verified: false,
    coverSeed: 4,
    gradient: ["#4a3a0d", "#ffa42b"],
    genres: GENRE_BY_ARTIST["a-boc"],
    bio: "Scottish duo Michael Sandison and Marcus Eoin. Warped, nostalgic electronica.",
  },
  {
    id: "a-jay",
    name: "周杰伦",
    listeners: "18,420,000",
    verified: true,
    coverSeed: 7,
    gradient: ["#2a0d3a", "#a44dff"],
    genres: GENRE_BY_ARTIST["a-jay"],
    bio: "台湾流行音乐天王。融合 R&B、嘻哈与中国风,改写了一代华语流行。",
  },
  {
    id: "a-cheer",
    name: "陈绮贞",
    listeners: "5,210,000",
    verified: true,
    coverSeed: 3,
    gradient: ["#0a3a2a", "#1ed760"],
    genres: GENRE_BY_ARTIST["a-cheer"],
    bio: "台湾创作歌手,清新民谣与独立流行的代表人物。",
  },
  {
    id: "a-utada",
    name: "宇多田ヒカル",
    listeners: "11,330,000",
    verified: true,
    coverSeed: 5,
    gradient: ["#3a0d10", "#f3727f"],
    genres: GENRE_BY_ARTIST["a-utada"],
    bio: "日本流行音乐巨星。《First Love》是日本史上最畅销专辑之一。",
  },
  {
    id: "a-yonezu",
    name: "米津玄師",
    listeners: "16,880,000",
    verified: true,
    coverSeed: 9,
    gradient: ["#240b04", "#ff8a3c"],
    genres: GENRE_BY_ARTIST["a-yonezu"],
    bio: "ボカロP出身のシンガーソングライター。緻密なポップを描く。",
  },
  {
    id: "a-iu",
    name: "IU",
    listeners: "20,640,000",
    verified: true,
    coverSeed: 11,
    gradient: ["#3a0d28", "#ff62a8"],
    genres: GENRE_BY_ARTIST["a-iu"],
    bio: "대한민국의 싱어송라이터이자 배우. 섬세한 보컬과 작사로 사랑받는다.",
  },
  {
    id: "a-eason",
    name: "陳奕迅",
    listeners: "12,910,000",
    verified: true,
    coverSeed: 1,
    gradient: ["#101012", "#8aa0b5"],
    genres: GENRE_BY_ARTIST["a-eason"],
    bio: "香港歌手,公认的「歌神」继承者,粤语流行的代表声音。",
  },
  {
    id: "a-daft",
    name: "Daft Punk",
    listeners: "27,450,000",
    verified: true,
    coverSeed: 3,
    gradient: ["#13031f", "#b15cff"],
    genres: GENRE_BY_ARTIST["a-daft"],
    bio: "Parisian electronic duo Thomas Bangalter and Guy-Manuel de Homem-Christo.",
  },
];

// ---- Classification · five orthogonal facets (NetEase-style) ----
const classification = {
  languages: [
    ["English", "#705fc5"],
    ["华语", "#dc148c"],
    ["日本語", "#e1118c"],
    ["한국어", "#e6116b"],
    ["粵語", "#bc5900"],
    ["Instrumental", "#477d95"],
  ],
  genres: [
    ["Indie", "#608108"],
    ["Dream Pop", "#d6457f"],
    ["Psychedelic", "#8400e7"],
    ["Electronic", "#705fc5"],
    ["Mandopop", "#dc148c"],
    ["J-Pop", "#e1118c"],
    ["K-Pop", "#e6116b"],
    ["Ambient", "#477d95"],
  ],
  scenes: [
    ["Commute", "#477d95"],
    ["Workout", "#e91429"],
    ["Study", "#27856a"],
    ["Sleep", "#503751"],
    ["Party", "#8d67ab"],
    ["Coffee", "#9c6b3f"],
  ],
  moods: [
    ["Calm", "#0d73ec"],
    ["Happy", "#e6a911"],
    ["Melancholy", "#5b6cae"],
    ["Hype", "#e91429"],
    ["Romantic", "#d6457f"],
    ["Nostalgic", "#7d6b3f"],
  ],
  themes: [
    ["Soundtrack", "#8400e7"],
    ["ACG", "#e1118c"],
    ["Covers", "#0d72ec"],
    ["Live", "#e91429"],
    ["Remix", "#705fc5"],
    ["Acoustic", "#27856a"],
  ],
};

// ---- Organization · Chart (ranked, with trend) ----
const num = (s: any) => parseInt(String(s).replace(/,/g, ""), 10) || 0;
const byPlays = [...tracks].sort((a, b) => num(b.plays) - num(a.plays));
const rotate = (arr: any[], n: number) => {
  const k = ((n % arr.length) + arr.length) % arr.length;
  return [...arr.slice(k), ...arr.slice(0, k)];
};
// delta: +n rose, -n fell, 0 steady, null = new entry
const mkEntries = (arr: any[], deltas: any[] = []) =>
  arr.map((t, i) => ({
    trackId: t.id,
    rank: i + 1,
    delta: i < deltas.length ? deltas[i] : 0,
    peak: Math.max(1, i + 1 - Math.max(0, deltas[i] || 0)),
  }));

const charts = [
  {
    id: "hot50",
    title: "Sonance Hot 50",
    type: "Hot",
    period: "Daily",
    updatedAt: "4 hours ago",
    seed: 0,
    gradient: ["#2a0716", "#ff5a3c"],
    entries: mkEntries(byPlays.slice(0, 10), [0, 1, -1, 2, 0, -2, 3, 1, 0, -1]),
  },
  {
    id: "weekly",
    title: "Global Weekly",
    type: "Global",
    period: "Weekly",
    updatedAt: "2 days ago",
    seed: 3,
    gradient: ["#0b1b3a", "#5b8cff"],
    entries: mkEntries(rotate(byPlays, 2).slice(0, 10), [1, -1, 0, 2, -3, 1, 0, -1, 2, 0]),
  },
  {
    id: "new",
    title: "New & Notable",
    type: "New",
    period: "Daily",
    updatedAt: "1 day ago",
    seed: 8,
    gradient: ["#101012", "#8aa0b5"],
    entries: mkEntries(rotate(tracks, 15).slice(0, 10), [
      null,
      null,
      1,
      null,
      0,
      2,
      null,
      1,
      null,
      0,
    ]),
  },
  {
    id: "cpop",
    title: "华语流行榜",
    type: "Genre",
    period: "Weekly",
    updatedAt: "1 day ago",
    seed: 5,
    gradient: ["#13031f", "#b15cff"],
    entries: mkEntries(
      [tracks[15], tracks[23], tracks[17], tracks[16], tracks[24]].filter(Boolean),
      [1, 0, -1, 2, 0],
    ),
  },
  {
    id: "late",
    title: "Late Night",
    type: "Mood",
    period: "Daily",
    updatedAt: "5 hours ago",
    seed: 6,
    gradient: ["#031a12", "#1ed98a"],
    entries: mkEntries(rotate(tracks, 6).slice(0, 10), [0, 1, 0, -1, 2, 0, -2, 1, 0, 1]),
  },
  {
    id: "lofi",
    title: "Top Lo-fi",
    type: "Genre",
    period: "Weekly",
    updatedAt: "4 days ago",
    seed: 10,
    gradient: ["#240b04", "#ff8a3c"],
    entries: mkEntries(rotate(byPlays, 7).slice(0, 10), [-1, 1, 0, 0, 2, -1, 0, 1, 0, -1]),
  },
];

// ---- Organization · Radio (endless seeded streams + podcasts) ----
const radios = [
  {
    id: "fm",
    title: "Personal FM",
    type: "personal",
    sub: "Endless stream tuned to you",
    seed: 4,
    gradient: ["#13031f", "#b15cff"],
  },
  {
    id: "artist",
    title: "Artist Radio",
    type: "artist",
    sub: "Songs in this artist's orbit",
    seed: 0,
    gradient: ["#1a0d3a", "#7755ff"],
  },
  {
    id: "genre",
    title: "Genre Radio",
    type: "genre",
    sub: "A continuous mood",
    seed: 2,
    gradient: ["#0a3a2a", "#1ed760"],
  },
  {
    id: "pod",
    title: "Podcasts",
    type: "podcast",
    sub: "Talk & shows, by the episode",
    seed: 9,
    gradient: ["#2a0420", "#ff4fa3"],
  },
];

// ---- Consumption · Comments (attached to a Song; "hot" sorted by likes) ----
type MockComment = {
  id: string;
  user: string;
  seed: number;
  text: string;
  likes: number;
  time: string;
};
const comments: MockComment[] = [
  {
    id: "c1",
    user: "moonriver",
    seed: 1,
    text: "This one rebuilt my whole evening. The bridge at 2:14 is unreal.",
    likes: 1284,
    time: "2 days ago",
  },
  {
    id: "c2",
    user: "kai_____",
    seed: 3,
    text: "Found this at 3am and now it lives in my head rent free.",
    likes: 902,
    time: "3 days ago",
  },
  {
    id: "c3",
    user: "veraa",
    seed: 5,
    text: "The reverb on the vocals — chef's kiss. On repeat all week.",
    likes: 564,
    time: "5 days ago",
  },
  {
    id: "c4",
    user: "tin.ear",
    seed: 7,
    text: "Came for the cover, stayed for the production. Bravo.",
    likes: 410,
    time: "a week ago",
  },
  {
    id: "c5",
    user: "nightbus",
    seed: 9,
    text: "Played this on a long drive, felt like the credits of a film.",
    likes: 332,
    time: "a week ago",
  },
  {
    id: "c6",
    user: "echo.lab",
    seed: 11,
    text: "That outro fade is the most peaceful 20 seconds of my day.",
    likes: 221,
    time: "2 weeks ago",
  },
];

export const MOCK = {
  data,
  playlists: playlists as unknown as VibeCollection[],
  albums: albums as unknown as VibeCollection[],
  artists: artists as unknown as VibeArtist[],
  charts: charts as unknown as VibeCollection[],
  radios,
  classification,
  comments,
};
