// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlbumDetail(arg1) {
  return window['go']['backend']['Library']['AlbumDetail'](arg1);
}

export function Albums() {
  return window['go']['backend']['Library']['Albums']();
}

export function AllTracks() {
  return window['go']['backend']['Library']['AllTracks']();
}

export function ArtistDetail(arg1) {
  return window['go']['backend']['Library']['ArtistDetail'](arg1);
}

export function Artists() {
  return window['go']['backend']['Library']['Artists']();
}

export function Home() {
  return window['go']['backend']['Library']['Home']();
}

export function Lyric(arg1) {
  return window['go']['backend']['Library']['Lyric'](arg1);
}

export function PickAndScan() {
  return window['go']['backend']['Library']['PickAndScan']();
}

export function PickFolder() {
  return window['go']['backend']['Library']['PickFolder']();
}

export function ScanFolder(arg1) {
  return window['go']['backend']['Library']['ScanFolder'](arg1);
}

export function Search(arg1) {
  return window['go']['backend']['Library']['Search'](arg1);
}

export function TrackCount() {
  return window['go']['backend']['Library']['TrackCount']();
}

export function Tracks(arg1) {
  return window['go']['backend']['Library']['Tracks'](arg1);
}
