// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AlbumDetail(arg1:string):Promise<backend.AlbumDetail>;

export function Albums():Promise<Array<backend.Album>>;

export function AllTracks():Promise<Array<backend.Track>>;

export function ArtistDetail(arg1:string):Promise<backend.ArtistDetail>;

export function Artists():Promise<Array<backend.Artist>>;

export function Home():Promise<backend.Home>;

export function Lyric(arg1:string):Promise<string>;

export function PickAndScan():Promise<backend.ScanResult>;

export function PickFolder():Promise<string>;

export function ScanFolder(arg1:string):Promise<backend.ScanResult>;

export function Search(arg1:string):Promise<backend.SearchResult>;

export function StreamURL(arg1:string):Promise<string>;

export function TrackCount():Promise<number>;

export function Tracks(arg1:Array<string>):Promise<Array<backend.Track>>;
