/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'

// Create Virtual Routes

const HomeIndexLazyImport = createFileRoute('/home/')()
const PlaylistPlaylistIdLazyImport = createFileRoute('/playlist/$playlistId')()
const AlbumAlbumIdLazyImport = createFileRoute('/album/$albumId')()

// Create/Update Routes

const HomeIndexLazyRoute = HomeIndexLazyImport.update({
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/home/index.lazy').then((d) => d.Route))

const PlaylistPlaylistIdLazyRoute = PlaylistPlaylistIdLazyImport.update({
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./pages/playlist/$playlistId.lazy').then((d) => d.Route),
)

const AlbumAlbumIdLazyRoute = AlbumAlbumIdLazyImport.update({
  path: '/album/$albumId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/album/$albumId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AlbumAlbumIdLazyRoute,
  PlaylistPlaylistIdLazyRoute,
  HomeIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/album/$albumId",
        "/playlist/$playlistId",
        "/home/"
      ]
    },
    "/album/$albumId": {
      "filePath": "album/$albumId.lazy.tsx"
    },
    "/playlist/$playlistId": {
      "filePath": "playlist/$playlistId.lazy.tsx"
    },
    "/home/": {
      "filePath": "home/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
