/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'

const HomeIndexLazyRouteImport = createFileRoute('/home/')()
const PlaylistPlaylistIdLazyRouteImport = createFileRoute(
  '/playlist/$playlistId',
)()
const AlbumAlbumIdLazyRouteImport = createFileRoute('/album/$albumId')()

const HomeIndexLazyRoute = HomeIndexLazyRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/home/index.lazy').then((d) => d.Route))
const PlaylistPlaylistIdLazyRoute = PlaylistPlaylistIdLazyRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./pages/playlist/$playlistId.lazy').then((d) => d.Route),
)
const AlbumAlbumIdLazyRoute = AlbumAlbumIdLazyRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/album/$albumId.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/album/$albumId': typeof AlbumAlbumIdLazyRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdLazyRoute
  '/home/': typeof HomeIndexLazyRoute
}
export interface FileRoutesByTo {
  '/album/$albumId': typeof AlbumAlbumIdLazyRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdLazyRoute
  '/home': typeof HomeIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/album/$albumId': typeof AlbumAlbumIdLazyRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdLazyRoute
  '/home/': typeof HomeIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/album/$albumId' | '/playlist/$playlistId' | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/album/$albumId' | '/playlist/$playlistId' | '/home'
  id: '__root__' | '/album/$albumId' | '/playlist/$playlistId' | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AlbumAlbumIdLazyRoute: typeof AlbumAlbumIdLazyRoute
  PlaylistPlaylistIdLazyRoute: typeof PlaylistPlaylistIdLazyRoute
  HomeIndexLazyRoute: typeof HomeIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AlbumAlbumIdLazyRoute: AlbumAlbumIdLazyRoute,
  PlaylistPlaylistIdLazyRoute: PlaylistPlaylistIdLazyRoute,
  HomeIndexLazyRoute: HomeIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
