// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Library is the Wails-bound adapter over the application service: it converts
 * string ids at the JS boundary, delegates each use case to the service, and
 * projects domain entities to wire DTOs (adding loopback URLs). The bound method
 * signatures + DTO shapes are the frontend contract, so they stay stable.
 * 
 * Every bound method that reaches a use case takes a context as its first
 * parameter (StreamURL does not: it only rewrites a URL). Wails recognises that
 * shape, so it stays out of the generated TypeScript and the frontend never
 * passes one: what arrives is a context scoped to that single call, which Wails
 * cancels when the caller abandons its promise.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AlbumDetail(id: string): $CancellablePromise<$models.AlbumDetailResult> {
    return $Call.ByID(2463934050, id);
}

export function AllTracks(): $CancellablePromise<$models.Track[] | null> {
    return $Call.ByID(1801758375);
}

export function ArtistDetail(id: string): $CancellablePromise<$models.ArtistDetailResult> {
    return $Call.ByID(3681162230, id);
}

export function Home(): $CancellablePromise<$models.Home> {
    return $Call.ByID(4006173507);
}

/**
 * Lyric returns a track's raw sidecar lyric text (LRC), "" when it has none. The
 * frontend parses the LRC into timed lines, so no wire DTO is needed.
 */
export function Lyric(id: string): $CancellablePromise<string> {
    return $Call.ByID(1084171735, id);
}

export function PickAndScan(): $CancellablePromise<$models.ScanResult> {
    return $Call.ByID(2592932683);
}

export function Search(query: string): $CancellablePromise<$models.SearchResult> {
    return $Call.ByID(1519698040, query);
}

/**
 * StreamURL maps a playback URL to a loopback, CORS-clean URL: our own /media is
 * returned unchanged, while a valid public remote URL is wrapped in the
 * authenticated /stream byte-proxy. Invalid/private targets fail closed to "".
 * The frontend uses it only for Web Audio analysis probes; audible playback
 * remains on the provider/native URL.
 */
export function StreamURL(raw: string): $CancellablePromise<string> {
    return $Call.ByID(3193510517, raw);
}

export function Tracks(ids: string[] | null): $CancellablePromise<$models.Track[] | null> {
    return $Call.ByID(3685929112, ids);
}
