// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Album {
    "id": string;
    "name": string;
    "artistId": string;
    "artist": string;
    "year": number;
    "trackCount": number;
    "coverUrl": string;
    "addedAt": number;
}

export interface AlbumDetail {
    "album": Album;
    "tracks": Track[] | null;
}

export interface AlbumDetailResult {
    "status": LookupStatus;
    "detail": AlbumDetail;
}

export interface Artist {
    "id": string;
    "name": string;
    "albumCount": number;
    "trackCount": number;
    "coverUrl": string;
}

export interface ArtistDetail {
    "artist": Artist;
    "albums": Album[] | null;
    "tracks": Track[] | null;
}

export interface ArtistDetailResult {
    "status": LookupStatus;
    "detail": ArtistDetail;
}

export interface Home {
    "recentTracks": Track[] | null;
    "albums": Album[] | null;
    "artists": Artist[] | null;
}

export enum LookupStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LookupFound = "found",
    LookupNotFound = "notFound",
};

export interface ScanResult {
    "folder": string;
    "scanned": number;
    "added": number;
    "total": number;
    "status": ScanStatus;
    "durationMs": number;
}

export enum ScanStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ScanCancelled = "cancelled",
    ScanPartial = "partial",
    ScanComplete = "complete",
};

export interface SearchResult {
    "tracks": Track[] | null;
    "albums": Album[] | null;
    "artists": Artist[] | null;
}

export interface Track {
    "id": string;
    "title": string;
    "albumId": string;
    "album": string;
    "artistId": string;
    "artist": string;
    "trackNumber": number;
    "discNumber": number;
    "durationMs": number;
    "year": number;
    "genre": string;
    "playUrl": string;
    "coverUrl": string;
    "addedAt": number;
}
